{% set name = "pymorphy3-dicts-ru" %}
{% set version = "2.4.417150.4580142" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymorphy3-dicts-ru-{{ version }}.tar.gz
  sha256: 39ab379d4ca905bafed50f5afc3a3de6f9643605776fbcabc4d3088d4ed382b0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pymorphy3_dicts_ru
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/no-plagiarism/pymorphy3-dicts
  dev_url: https://github.com/no-plagiarism/pymorphy3-dicts
  doc_url: https://github.com/no-plagiarism/pymorphy3-dicts
  summary: Ukrainian dictionaries for pymorphy3
  description: |
    Ukrainian dictionaries for pymorphy3
  license: GPL-3.0-or-later
  license_family: GPL
  license_url: https://github.com/no-plagiarism/pymorphy3-dicts/blob/master/LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
